### ISSUE TITLE
Nhưng mà trong file changed làm gì có cái migration nào add nó vào đâu em?

### ISSUE THREAD

**Issue by ghost** [hieuduy0212/sample_app#7]
Nhưng mà trong file changed làm gì có cái migration nào add nó vào đâu em?

_Originally posted by @nhatnq-3267 in https://github.com/hieuduy0212/sample_app/pull/6#discussion_r1496970090_

**Comment by hieuduy0212** [comment]
ui em thấy vấn đề rồi. hình như e làm cái thay đổi í lộn vào nhánh chapter 8 rồi@
